stages:
  - init
  - validate
  - apply

variables:
  TF_STATE_STORAGE_ACCOUNT: $TF_STATE_STORAGE_ACCOUNT
  TF_STATE_CONTAINER: $TF_STATE_CONTAINER
  TF_STATE_KEY: $TF_STATE_KEY
  ARM_CLIENT_ID: $ARM_CLIENT_ID
  ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
  ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
  ARM_TENANT_ID: $ARM_TENANT_ID

terraform-init:
  stage: init
  image: hashicorp/terraform:1.5.7
  script:
    - terraform init \
      -backend-config="storage_account_name=${TF_STATE_STORAGE_ACCOUNT}" \
      -backend-config="container_name=${TF_STATE_CONTAINER}" \
      -backend-config="key=${TF_STATE_KEY}" \
      -backend-config="resource_group_name=tfstate-rg"
  artifacts:
    paths:
      - .terraform

terraform-validate:
  stage: validate
  image: hashicorp/terraform:1.5.7
  script:
    - terraform validate
  dependencies:
    - terraform-init

terraform-apply:
  stage: apply
  image: hashicorp/terraform:1.5.7
  script:
    - terraform apply -auto-approve
  dependencies:
    - terraform-validate
  only:
    - main