name: 'Apply External Terraform Configuration'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Clone External Terraform Repository
        run: |
          git clone https://github.com/DiomedesAuRaa/aws-terraform-stack.git

      - name: Verify Cloned Files
        run: ls -la aws-terraform-stack/eks
 
      - name: Create terraform.tfvars
        working-directory: aws-terraform-stack/eks
        run: |
          cat <<EOF > terraform.tfvars
          aws_access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          region         = "us-east-1"
          EOF        
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: aws-terraform-stack/eks
        run: terraform init

      - name: Terraform Plan
        working-directory: aws-terraform-stack/eks
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: aws-terraform-stack/eks
        run: terraform apply -var-file=terraform.tfvars -auto-approve